### ISSUE TITLE
INFORMATION REQUIRED

### ISSUE THREAD

**Issue by mudassar111** [BugzTheBunny/streamlit_navbar#2]
@BugzTheBunny Hello Brother, Can you please tell me how are you running this app on your computer? I am facing issues.

**Comment by Hassi34** [comment]
@mudassar111 did you get the solution ? for me it says that the streamlit is not allowing the connection. @BugzTheBunny  can you please help?

**Comment by BugzTheBunny** [comment]
Hi @Hassi34  and @mudassar111 

I already answered @mudassar111 regarding his question previously, the problem was not in the code over here, it was because of a python mismatch.

@Hassi34 could you elaborate a bit more? the only reason I can think of is if you are not using the correct port.
